all:
  hosts:
    cp1:
      ansible_host: 51.250.47.243
      ansible_user: yc-user
    node1:
      ansible_host: 51.250.38.183
      ansible_user: yc-user
    node2:
      ansible_host: 51.250.33.181
      ansible_user: yc-user
  children:
    kube_control_plane:
      hosts:
        cp1:
    kube_node:
      hosts:
        cp1:
        node1:
        node2:
    etcd:
      hosts:
        cp1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
